export const resList = [
  {
    info: {
      id: "97272",
      name: "Ramsar Bakery",
      cloudinaryImageId: "rmf8gsxyxtgejfj73dxe",
      locality: "Congress House Road",
      areaName: "Shivaji Nagar",
      costForTwo: "₹300 for two",
      cuisines: [
        "Bakery",
        "Snacks",
        "Desserts",
        "Fast Food",
        "Beverages",
        "Indian",
        "Street Food",
      ],
      avgRating: 4.2,
      veg: true,
      parentId: "166716",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 16,
        lastMileTravel: 0.7,
        serviceability: "SERVICEABLE",
        slaString: "16 mins",
        lastMileTravelString: "0.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 23:55:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/ramsar-bakery-congress-house-road-shivaji-nagar-pune-97272",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "471851",
      name: "Cafe Brewing Italiana",
      cloudinaryImageId: "e07a9469cdbb6f4c9d6e3b6da0e56c25",
      locality: "Shivaji Nagar",
      areaName: "Shivaji Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Italian", "Pizzas", "Beverages"],
      avgRating: 3.8,
      veg: true,
      parentId: "314150",
      avgRatingString: "3.8",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 27,
        lastMileTravel: 1.2,
        serviceability: "SERVICEABLE",
        slaString: "27 mins",
        lastMileTravelString: "1.2 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 23:59:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/cafe-brewing-italiana-shivaji-nagar-pune-471851",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "288928",
      name: "Casablanca",
      cloudinaryImageId: "mx7ba8wjvs6vjejdlbpf",
      locality: "Shivaji Nagar",
      areaName: "Shivaji Nagar",
      costForTwo: "₹600 for two",
      cuisines: ["Continental"],
      parentId: "9291",
      avgRatingString: "--",
      sla: {
        deliveryTime: 28,
        lastMileTravel: 1.9,
        serviceability: "SERVICEABLE",
        slaString: "28 mins",
        lastMileTravelString: "1.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 23:59:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/casablanca-shivaji-nagar-pune-288928",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "776752",
      name: "Naad Bhramanti Cafe",
      cloudinaryImageId: "fcee676df41abe3fa8b474ece9d2b77d",
      locality: "Bhalekar Chawl",
      areaName: "Kothrud",
      costForTwo: "₹160 for two",
      cuisines: [
        "Beverages",
        "Italian-American",
        "Fast Food",
        "Snacks",
        "Chinese",
      ],
      avgRating: 3.2,
      veg: true,
      parentId: "462996",
      avgRatingString: "3.2",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 36,
        lastMileTravel: 3.6,
        serviceability: "SERVICEABLE",
        slaString: "36 mins",
        lastMileTravelString: "3.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 07:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "₹250 OFF",
        subHeader: "ABOVE ₹999",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/naad-bhramanti-cafe-bhalekar-chawl-kothrud-pune-776752",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "777295",
      name: "Balaji Snacks And Tea Center",
      cloudinaryImageId: "5232573be350da499676dbc81a256b75",
      locality: "Karve Road",
      areaName: "Kothrud",
      costForTwo: "₹150 for two",
      cuisines: ["Beverages", "South Indian", "Snacks"],
      avgRating: 4.5,
      veg: true,
      parentId: "463201",
      avgRatingString: "4.5",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 23,
        lastMileTravel: 3.6,
        serviceability: "SERVICEABLE",
        slaString: "23 mins",
        lastMileTravelString: "3.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 07:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/balaji-snacks-and-tea-center-karve-road-kothrud-pune-777295",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "790195",
      name: "THE ITALIAN PIZZASHOP",
      cloudinaryImageId: "8b35482c4e83db59a2ecc3b306fdcf52",
      locality: "Ghole Road",
      areaName: "Prabhat Road",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas", "Burgers"],
      avgRating: 3.5,
      parentId: "469466",
      avgRatingString: "3.5",
      totalRatingsString: "6",
      sla: {
        deliveryTime: 38,
        lastMileTravel: 4,
        serviceability: "SERVICEABLE",
        slaString: "38 mins",
        lastMileTravelString: "4.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 07:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/the-italian-pizzashop-ghole-road-prabhat-road-pune-790195",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "810281",
      name: "Wise Monks Pizzeria",
      cloudinaryImageId: "d390a6c080d7fa9a3a89f48100ca20b1",
      locality: "  pune dp road city point",
      areaName: " 17,Boat club road",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani"],
      veg: true,
      parentId: "483206",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3.8,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
        lastMileTravelString: "3.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/wise-monks-pizzeria-dp-road-city-point-17-boat-club-road-pune-810281",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "4086",
      name: "RushHrs",
      cloudinaryImageId: "pzaowbuaslyzc2pvbcek",
      locality: "Paud Road",
      areaName: "Kothrud",
      costForTwo: "₹400 for two",
      cuisines: ["American", "Burgers", "Salads", "Fast Food", "Desserts"],
      avgRating: 4.4,
      parentId: "791",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 26,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "26 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-10 00:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/rushhrs-paud-road-kothrud-pune-4086",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "455621",
      name: "Kokan Fresh Fish",
      cloudinaryImageId: "mqo3zy6g5xndcczskmog",
      locality: "Rahul Nagar",
      areaName: "Kothrud",
      costForTwo: "₹350 for two",
      cuisines: ["Maharashtrian", "Seafood"],
      avgRating: 4.3,
      parentId: "273715",
      avgRatingString: "4.3",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 53,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "53 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-01-03 14:30:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-c9ff05c4-7d08-48c2-b986-62af5f7784a0",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/kokan-fresh-fish-rahul-nagar-kothrud-pune-455621",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];
